# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

#!/usr/bin/env python3
"""Development-only self-signed certificate tool for the registry center.

Do not use certificates or private keys generated by this tool in production.
Production deployments must use certificates issued by a trusted public or
enterprise CA and follow the organization's certificate-management policy.

Usage:
    python -m generate_selfsign_cert <cert_dir> <cert_usage> [--dns HOST] [--ip ADDRESS] [--plain-key]
    python -m generate_selfsign_cert <cert_dir> serverAuth --issue-client <name>

    cert_dir:   Certificate directory path (e.g. etc/ssl)
    cert_usage: serverAuth (TLS communication) or dataSigning (data signing)

The password for the private key is entered interactively.
serverAuth defaults to localhost, 127.0.0.1 and ::1; explicit SAN options replace these defaults.

For serverAuth, deployment-ready files are produced alongside the raw ones:
    server.cer       TLS certificate (copy of server_RSA.cer)
    trust.cer        trust anchor (copy of server.cer)
    server_key.pem   encrypted private key (copy of server_key_RSA.pem)
    cert_pwd         key password without trailing newline

dataSigning writes sign.cer, sign_key.pem and cert_pwd in a separate directory
(e.g. etc/sign_cert), retaining the RSA-suffixed files for compatibility.
Existing raw files, deployment files and client credentials are never overwritten.

With --plain-key, server_key_nopass.pem (unencrypted key) is also written for
nginx and agent servers, which cannot decrypt the encrypted key themselves.
Protect it: it is written with owner-only permissions on Linux.

The self-signed server certificate doubles as its own CA (trust.cer), so with
verify_client=true client certificates can be issued from it:

    python -m generate_selfsign_cert <cert_dir> serverAuth --issue-client dev-proxy

writes <cert_dir>/<name>-client.cer / -client.key (unencrypted, owner-only on
Linux). Configure the calling client's TLS certificate and key with this
pair and its trusted CA with trust.cer. The password is read from cert_pwd
— no interaction needed.

The main backend reads the key password from etc/ssl/cert_pwd by default
(ssl_keyfile_password in server.conf). For another directory, configure
all four TLS paths explicitly.
"""

import argparse
import datetime
import os
import platform
import re
import stat
import sys

from common.cert.certificate_generator import CertificateGenerator
from common.util.password_util import input_password_with_validation

SERVER_CER = "server.cer"
TRUST_CER = "trust.cer"
SERVER_KEY = "server_key.pem"
CERT_PWD = "cert_pwd"
SIGN_CER = "sign.cer"
SIGN_KEY = "sign_key.pem"
PLAIN_KEY = "server_key_nopass.pem"
NAME_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9-]*")


def _owner_only(path: str) -> None:
    if platform.system().lower() == "linux":
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def _require_new_paths(paths: list[str]) -> None:
    """Refuse all existing entries, including directories and dangling symlinks."""
    existing = [path for path in paths if os.path.lexists(path)]
    if existing:
        raise FileExistsError("The tool refuses to overwrite: " + ", ".join(existing)
                              + "; generate into a different directory.")


def _write_new_files(contents: dict[str, bytes]) -> list[str]:
    """Create owner-only files exclusively; remove only our partial new bundle."""
    _require_new_paths(list(contents))
    created = []
    try:
        for path, data in contents.items():
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            created.append(path)
            with os.fdopen(fd, "wb") as stream:
                stream.write(data)
            _owner_only(path)
    except Exception:
        for path in created:
            os.unlink(path)
        raise
    return created


def _deployment_names(cert_usage: str, plain_key: bool = False) -> list[str]:
    if cert_usage not in ("serverAuth", "dataSigning"):
        raise ValueError("Certificate usage must be serverAuth or dataSigning")
    if cert_usage == "dataSigning" and plain_key:
        raise ValueError("--plain-key applies only to serverAuth certificates")
    if cert_usage == "serverAuth":
        names = [SERVER_CER, TRUST_CER, SERVER_KEY, CERT_PWD]
        if plain_key:
            names.append(PLAIN_KEY)
        return names
    return [SIGN_CER, SIGN_KEY, CERT_PWD]


def _write_deploy_files(cert_dir: str, password: str, plain_key: bool,
                        cert_usage: str = "serverAuth") -> list[str]:
    """Export TLS or signing material and its raw password, without overwriting.

    TLS and dataSigning must use separate directories. cert_pwd is plaintext
    for compatibility with both TLS password loading and AgentCardSigner.
    Protect the whole directory as a credential, not just the encrypted key.
    """
    from cryptography.hazmat.primitives import serialization

    paths = [os.path.join(cert_dir, name) for name in _deployment_names(cert_usage, plain_key)]
    _require_new_paths(paths)
    with open(os.path.join(cert_dir, "server_RSA.cer"), "rb") as stream:
        cert_data = stream.read()
    with open(os.path.join(cert_dir, "server_key_RSA.pem"), "rb") as stream:
        key_data = stream.read()
    key = serialization.load_pem_private_key(key_data, password=password.encode("utf-8"))
    if cert_usage == "serverAuth":
        contents = {paths[0]: cert_data, paths[1]: cert_data,
                    paths[2]: key_data, paths[3]: password.encode("utf-8")}
        if plain_key:
            contents[paths[4]] = key.private_bytes(
                serialization.Encoding.PEM,
                serialization.PrivateFormat.TraditionalOpenSSL,
                serialization.NoEncryption(),
            )
    else:
        contents = {paths[0]: cert_data, paths[1]: key_data, paths[2]: password.encode("utf-8")}
    return _write_new_files(contents)


def issue_client_cert(cert_dir: str, name: str) -> tuple[str, str]:
    """Issue a TLS client certificate signed by the generated server certificate.

    Requires the server certificate material from a prior generation in
    cert_dir (server_RSA.cer, server_key_RSA.pem, cert_pwd). The client
    certificate chains to trust.cer, so the backend accepts it when
    verify_client=true.
    """
    from cryptography import x509
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

    if not NAME_PATTERN.fullmatch(name):
        raise ValueError("client certificate name may contain letters, digits and dashes only")
    cert_path = os.path.join(cert_dir, f"{name}-client.cer")
    key_path = os.path.join(cert_dir, f"{name}-client.key")
    _require_new_paths([cert_path, key_path])
    raw_cert = os.path.join(cert_dir, "server_RSA.cer")
    raw_key = os.path.join(cert_dir, "server_key_RSA.pem")
    pwd_path = os.path.join(cert_dir, CERT_PWD)
    missing = [p for p in (raw_cert, raw_key, pwd_path) if not os.path.exists(p)]
    if missing:
        raise FileNotFoundError(
            "server certificate material missing: " + ", ".join(missing)
            + "; generate the server certificate first")

    with open(pwd_path, encoding="utf-8") as f:
        # strip(): tolerate hand-written password files with a trailing newline,
        # matching load_cert_password() semantics on the backend side.
        password = f.read().strip()
    with open(raw_cert, "rb") as f:
        ca_cert = x509.load_pem_x509_certificate(f.read())
    with open(raw_key, "rb") as f:
        ca_key = serialization.load_pem_private_key(f.read(), password=password.encode("utf-8"))

    constraints = ca_cert.extensions.get_extension_for_class(x509.BasicConstraints).value
    usage = ca_cert.extensions.get_extension_for_class(x509.KeyUsage).value
    if not constraints.ca or not usage.key_cert_sign:
        raise ValueError("existing certificate cannot issue client certificates; generate serverAuth first")
    if ca_cert.public_key().public_numbers() != ca_key.public_key().public_numbers():
        raise ValueError("server certificate and private key do not match")

    client_key = rsa.generate_private_key(public_exponent=65537, key_size=3072)
    now = datetime.datetime.now(datetime.UTC)
    cert = (x509.CertificateBuilder()
            .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, name)]))
            .issuer_name(ca_cert.subject)
            .public_key(client_key.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(now)
            .not_valid_after(min(now + datetime.timedelta(days=3650), ca_cert.not_valid_after_utc))
            .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
            .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.CLIENT_AUTH]), critical=False)
            .sign(ca_key, hashes.SHA256()))

    _write_new_files({
        cert_path: cert.public_bytes(serialization.Encoding.PEM),
        key_path: client_key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        ),
    })
    return cert_path, key_path


def generate_self_signed_cert(cert_dir: str, cert_usage: str, password: str, *,
                              dns_names: list[str] | None = None,
                              ip_addresses: list[str] | None = None) -> bool:
    try:
        generator = CertificateGenerator(key_algorithm='RSA', dns_names=dns_names, ip_addresses=ip_addresses)
        success = generator.generate_self_signed_cert(cert_dir, cert_usage, password)

        if success:
            print(f"Successfully generated self-signed certificates in {cert_dir}")
            return True
        else:
            existing = [name for name in ("server_RSA.cer", "server_key_RSA.pem")
                        if os.path.lexists(os.path.join(cert_dir, name))]
            if existing:
                print(f"Failed: certificate files already exist in {cert_dir}: "
                      f"{', '.join(existing)}")
                print("The tool refuses to overwrite. Remove them to regenerate"
                      " (regeneration issues a NEW key pair: re-issue client"
                      " certificates and redistribute trust material), or"
                      " generate into a different directory.")
            else:
                print("Failed to generate certificates (check the error output above)")
            return False
    except Exception as e:
        print(f"Error generating certificates: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("cert_dir", help="New certificate directory; existing files are not overwritten")
    parser.add_argument("cert_usage", choices=("serverAuth", "dataSigning"))
    parser.add_argument("--dns", action="append", help="DNS SAN; repeat for multiple hostnames")
    parser.add_argument("--ip", action="append", help="IP SAN; repeat for IPv4 or IPv6 addresses")
    parser.add_argument("--plain-key", action="store_true",
                        help="serverAuth only: also write the unencrypted server_key_nopass.pem "
                             "for nginx and agent servers")
    parser.add_argument("--issue-client", metavar="NAME",
                        help="serverAuth only: issue a TLS client certificate named NAME, signed "
                             "by the existing server certificate (requires cert_pwd); "
                             "configure the returned pair in your client")
    args = parser.parse_args()
    if args.cert_usage == "dataSigning" and (args.dns or args.ip):
        parser.error("--dns and --ip apply only to serverAuth certificates")
    if args.cert_usage == "dataSigning" and args.plain_key:
        parser.error("--plain-key applies only to serverAuth certificates")
    if args.issue_client:
        if args.cert_usage != "serverAuth":
            parser.error("--issue-client issues a TLS client certificate; use serverAuth")
        if args.dns or args.ip or args.plain_key:
            parser.error("--issue-client issues a certificate from existing material; "
                         "it cannot be combined with --dns/--ip/--plain-key")
        if not NAME_PATTERN.fullmatch(args.issue_client):
            parser.error("client certificate name may contain letters, digits and dashes only")

        try:
            cert_path, key_path = issue_client_cert(args.cert_dir, args.issue_client)
        except Exception as e:
            print(f"Error issuing client certificate: {e}")
            sys.exit(1)
        print("Client certificate issued:")
        print(f"  {cert_path}")
        print(f"  {key_path}")
        print("For other clients (e.g. nginx upstream): configure proxy_ssl_certificate/"
              "proxy_ssl_certificate_key with this pair and proxy_ssl_trusted_certificate "
              "pointing at trust.cer.")
        sys.exit(0)

    try:
        names = ["server_RSA.cer", "server_key_RSA.pem"] + _deployment_names(args.cert_usage, args.plain_key)
        _require_new_paths([os.path.join(args.cert_dir, name) for name in names])
    except FileExistsError as exc:
        print(f"Error: {exc}")
        sys.exit(1)

    password = input_password_with_validation("Enter private key password")
    if password != password.strip():
        parser.error("private key password must not start or end with whitespace")
    if password.startswith("enc:v1:"):
        parser.error("private key password must not start with reserved config-cipher prefix enc:v1:")

    if not generate_self_signed_cert(args.cert_dir, args.cert_usage, password,
                                     dns_names=args.dns, ip_addresses=args.ip):
        sys.exit(1)

    try:
        written = _write_deploy_files(args.cert_dir, password, plain_key=args.plain_key,
                                      cert_usage=args.cert_usage)
    except Exception as e:
        print(f"Error writing deployment files: {e}")
        sys.exit(1)
    print("Deployment-ready files written:")
    for path in written:
        print(f"  {path}")
    if args.cert_usage == "serverAuth":
        print("TLS defaults use etc/ssl/server.cer, server_key.pem, cert_pwd and trust.cer. "
              "For another directory, set all four ssl_* paths in server.conf.")
        if not args.plain_key:
            print("For nginx, select --plain-key when generating into a new directory.")
    else:
        print("Signing defaults use etc/sign_cert/sign.cer, sign_key.pem and cert_pwd. "
              "For another directory, set jwk_cert_path, jwk_private_key_path and "
              "jwk_private_key_password in server.conf.")
    print("cert_pwd stores the plaintext password. Keep the directory private; never commit it. "
          "On Windows restrict access using the service account's ACL.")
    sys.exit(0)


if __name__ == "__main__":
    main()
